counting_votes/config/routes.rb
Rails.application.routes.draw do
  get 'static/index'

  resources :votes

  resources :committees_voivodeships

  resources :committees

  resources :voivodeships

  resources :constituencies

  resources :users

  resource :user_session, :only => [:new, :create, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root :to => 'static#index'
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  

end

counting_votes/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

counting_votes/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

counting_votes/app/models/committee.rb
class Committee < ActiveRecord::Base
  has_many :votes
  has_many :voivodeships
  has_and_belongs_to_many :constituencies
   
  has_attached_file :avatar, 
  					:styles => { :medium => "300x300>", :thumb => "100x100>" }, 
  					:default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

validates :name, presence: true

end

counting_votes/app/models/committees_voivodeship.rb
class CommitteesVoivodeship < ActiveRecord::Base
  belongs_to :committee
  belongs_to :voivodeship
end

counting_votes/app/models/constituency.rb
class Constituency < ActiveRecord::Base
  belongs_to :voivodeship
  has_many :votes
  has_one :user
  has_and_belongs_to_many :committees

  validates :name, presence: true
  validates :mandate_number, presence: true, numericality: true
  validates :authorized_number, presence: true, numericality: true
  validates :empty_votes, presence: true, numericality: true
  validates :many_votes, presence: true, numericality: true
  validates :other_votes, presence: true, numericality: true
  validates :given_cards, presence: true, numericality: true
  validates :returned_cards, presence: true, numericality: true
  
  @constituencies = Constituency.all.map do |constituency|
    [ constituency.name, constituency.id]
  end

end

counting_votes/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :constituency

  ROLES = %w[local central admin]

  def user_params
    params.require(:user).permit(:admin)
  end

  acts_as_authentic do |config|
    config.validate_login_field = false
    config.validate_email_field = false
    config.validate_password_field = false
    config.crypted_password_field = :crypted_password
    config.require_password_confirmation = true
  end

  def role?(base_role)
    ROLES.index(base_role.to_s) <= ROLES.index(role)
  end

  @constituencies = Constituency.all.map do |constituency|
    [ constituency.name, constituency.id]
  end

end

counting_votes/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  login_field :login

  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
end

counting_votes/app/models/voivodeship.rb
class Voivodeship < ActiveRecord::Base
	has_many :constituencies
	
	
	validates :name, presence: true
end

counting_votes/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :committee
  belongs_to :constituency
end

counting_votes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

   protect_from_forgery
   helper_method :current_user_session, :current_user

  private
  def current_user_session
    return @current_user if defined?(@current_user_sesssion)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end

  def authenticate
	if !current_user
	  redirect_to new_user_session_path
	end
  end
end

counting_votes/app/controllers/committees_controller.rb
class CommitteesController < InheritedResources::Base

  def index
    @committees = Committee.all
  end

  def new
    @committee = Committee.new
  end

  def show
    @committee = Committee.find(params[:id])
  end

  def create
  @committee = Committee.create( committee_params )
  
  respond_to do |format|
      if @committee.save
        format.html { redirect_to @committee, notice: 'Committee was successfully created.' }
        format.json { render :show, status: :created, location: @committee }
      else
        format.html { render :new }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
  end

end


private

  def set_committee
    @committee = Committee.find(params[:id])
  end

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def committee_params
    params.require(:committee).permit(:name, :avatar, :committee_id)
  end

end

counting_votes/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

counting_votes/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      flash[:notice] = "Registration successful."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def edit
  	@user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:notice] = "Successfully updated profile."
      redirect_to admin_root_url
    else
      render :action => 'edit'
    end
  end

private
  def set_user
     @user = User.find(params[:id])
  end

  def user_params
      params.require(:user).permit(:login, :password, :password_confirmation, :password_salt, :persistence_token, :email, :role, :constituency_id)
  end
  
end

counting_votes/app/controllers/voivodeships_controller.rb
class VoivodeshipsController < InheritedResources::Base
  
  def index
    @voivodeships = Voivodeship.all
  end

  def show
     @voivodeship = Voivodeship.find(params[:id])
  end



  private

    def voivodeship_params
      params.require(:voivodeship).permit(:name, :authorized_number, :mandate_number)
    end
end

counting_votes/app/controllers/votes_controller.rb
class VotesController < InheritedResources::Base
  
  def create
  @vote = Vote.create( vote_params )
  @constituency = Constituency.find(params[:id])
  @committee = Committee.find(params[:id])   
  end

  private

    def vote_params
      params.require(:vote).permit(:number, :committee_id, :constituency_id)
    end

    def committee_params
    params.require(:committee).permit(:name, :committee_id)
    end

    def constituency_params
      params.require(:constituency).permit(:name, :empty_votes, :many_votes, :other_votes, :given_cards, :returned_cards, :voivodeship_id)
    end
end

counting_votes/app/helpers/application_helper.rb
module ApplicationHelper
end

counting_votes/app/helpers/committees_helper.rb
module CommitteesHelper
end

counting_votes/app/helpers/constituencies_helper.rb
module ConstituenciesHelper
end

counting_votes/app/helpers/index_helper.rb
module IndexHelper
end

counting_votes/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

counting_votes/app/helpers/users_helper.rb
module UsersHelper
end

counting_votes/app/helpers/voivodeships_helper.rb
module VoivodeshipsHelper
end

counting_votes/app/helpers/votes_helper.rb
module VotesHelper
end

counting_votes/app/views/admin/users/change_constituency.html.erb
<%= form_for @user do |f| %>
    <p>
      <%= f.label :constituency %> <br />
      <%= f.select ("constituency", "constituency_id", Constituency.all.collect {|con| [ con.name, con.id ] }, {prompt: 'Select Constituency'})%>

    <p><%= f.submit "Submit" %> </p>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

counting_votes/app/views/admin/users/change_role.html.erb
<%= form_for @user do |f| %>
    <p>
      <%= f.label :role %> <br />
      <%= f.select :role, options_for_select(User::ROLES) %>

    <p><%= f.submit "Submit" %> </p>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

counting_votes/app/views/admin/voivodeships/show_constituencies.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @constituency.name %>
</p>

<p>
  <strong>Mandate number:</strong>
  <%= @constituency.mandate_number %>
</p>

<p>
  <strong>Authorized number:</strong>
  <%= @constituency.authorized_number %>
</p>

<p>
  <strong>Empty votes:</strong>
  <%= @constituency.empty_votes %>
</p>

<p>
  <strong>Many votes:</strong>
  <%= @constituency.many_votes %>
</p>

<p>
  <strong>Other votes:</strong>
  <%= @constituency.other_votes %>
</p>

<p>
  <strong>Given cards:</strong>
  <%= @constituency.given_cards %>
</p>

<p>
  <strong>Returned cards:</strong>
  <%= @constituency.returned_cards %>
</p>

<p>
  <strong>Voivodeship:</strong>
  <%= @constituency.voivodeship.name %>
</p>

<%= link_to 'Edit', edit_constituency_path(@constituency) %> |
<%= link_to 'Back', constituencies_path %>

counting_votes/app/views/committees/_committee_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-4">
      <%= image_tag committee.logo.url(:thumb) %>
    </div>
    <div class="col-xs-4">
      <h4><%= committee.name %></h4>
    </div>
    <div class="col-xs-4">
    </div>
      </div>
    </div>

counting_votes/app/views/committees/_form.html.erb
<%= form_for(@committee) do |f| %>
  <% if @committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% @committee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

counting_votes/app/views/committees/edit.html.erb
<h1>Editing Committee</h1>
 
<%= render 'form' %>

<%= link_to 'Show', @committee %> |
<%= link_to 'Back', committees_path %>

counting_votes/app/views/committees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Committees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committees.each do |committee| %>
      <tr>
        <td><%= committee.name %></td>
        <td><%= committee.avatar %></td>
        <td><%= link_to 'Show', committee %></td>
        <td><%= link_to 'Edit', edit_committee_path(committee) %></td>
        <td><%= link_to 'Destroy', committee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Committee', new_committee_path %>

counting_votes/app/views/committees/new.html.erb
<h1>New committee</h1>

<%= render 'form' %>

<%= link_to 'Back', committees_path %>

counting_votes/app/views/committees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @committee.name %>
</p>

<p>
  <%= image_tag @committee.avatar.url %>
</p>

<%= link_to 'Edit', edit_committee_path(@committee) %> |
<%= link_to 'Back', committees_path %>

counting_votes/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, f.object.new_record? ? nil : "Change password" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.text_field :admin %>
  </div>
  <div class="field">
    <%= f.label :constituency_id %><br>
    <%= f.text_field :constituency_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

counting_votes/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

counting_votes/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

counting_votes/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Role</th>
      <th>Constituency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.constituency_id %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

counting_votes/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

counting_votes/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Constituency:</strong>
  <%= @user.constituency_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

counting_votes/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

counting_votes/app/views/voivodeships/_form.html.erb
<%= form_for(@voivodeship) do |f| %>
  <% if @voivodeship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voivodeship.errors.count, "error") %> prohibited this voivodeship from being saved:</h2>

      <ul>
      <% @voivodeship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  <% end %>

counting_votes/app/views/voivodeships/edit.html.erb
<h1>Editing Voivodeship</h1>

<%= render 'form' %>

<%= link_to 'Show', @voivodeship %> |
<%= link_to 'Back', voivodeships_path %>

counting_votes/app/views/voivodeships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Voivodeships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voivodeships.each do |voivodeship| %>
      <tr>
        <td><%= voivodeship.name %></td>
        <td><%= link_to 'Show', voivodeship %></td>
        <td><%= link_to 'Edit', edit_voivodeship_path(voivodeship) %></td>
        <td><%= link_to 'Destroy', voivodeship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voivodeship', new_voivodeship_path %>

counting_votes/app/views/voivodeships/new.html.erb
<h1>New Voivodeship</h1>

<%= render 'form' %>

<%= link_to 'Back', voivodeships_path %>

counting_votes/app/views/voivodeships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @voivodeship.name %>
</p>

<%= link_to 'Edit', edit_voivodeship_path(@voivodeship) %> |
<%= link_to 'Back', voivodeships_path %>

counting_votes/app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Add voting result</h1>


  <h2><%= @constituency.name %></h2>
  <div class="field">
    <%= f.label :committee %><br>
    <%= f.select :committee, options_for_select(Committee.all.map{|u| ["#{u.name}", u.id]}) %>
  </div>
  <div class="field">
    <%= f.hidden_field :constituency_id, :value => @constituency.id %>
  </div>
   <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :empty_votes %><br>
    <%= f.number_field :empty_votes %>
  </div>
  <div class="field">
    <%= f.label :many_votes %><br>
    <%= f.number_field :many_votes %>
  </div>
  <div class="field">
    <%= f.label :other_votes %><br>
    <%= f.number_field :other_votes %>
  </div>
  <div class="field">
    <%= f.label :given_cards %><br>
    <%= f.number_field :given_cards %>
  </div>
  <div class="field">
    <%= f.label :returned_cards %><br>
    <%= f.number_field :returned_cards %>
  </div>
  <div class="field">
    <%= f.hidden_field :voivodeship_id, :value => @voivodeship.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>  

counting_votes/app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

counting_votes/app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Votes</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Committee</th>
      <th>Constituency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.number %></td>
        <td><%= vote.committee.name %></td>
        <td><%= vote.constituency.name %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

counting_votes/app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

counting_votes/app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @vote.number %>
</p>

<p>
  <strong>Committee:</strong>
  <%= @vote.committee.name %>
</p>

<p>
  <strong>Constituency:</strong>
  <%= @vote.constituency.name %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>