counting_votes/config/routes.rb
Rails.application.routes.draw do
  get 'static/index'

  resources :votes

  resources :committees_voivodeships

  resources :committees

  resources :voivodeships

  resources :constituencies

  resources :users

  resource :user_session, :only => [:new, :create, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root :to => 'static#index'
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  

end

counting_votes/app/models/constituency.rb
class Constituency < ActiveRecord::Base
  belongs_to :voivodeship
  has_many :votes
  has_one :user
  has_and_belongs_to_many :committees

  validates :name, presence: true
  validates :mandate_number, presence: true, numericality: true
  validates :authorized_number, presence: true, numericality: true
  validates :empty_votes, presence: true, numericality: true
  validates :many_votes, presence: true, numericality: true
  validates :other_votes, presence: true, numericality: true
  validates :given_cards, presence: true, numericality: true
  validates :returned_cards, presence: true, numericality: true
  
  @constituencies = Constituency.all.map do |constituency|
    [ constituency.name, constituency.id]
  end

end

counting_votes/app/controllers/constituencies_controller.rb
class ConstituenciesController < InheritedResources::Base

  def index
    @constituencies = Constituency.all
  end

  def show
     @constituency = Constituency.find(params[:id])
  end

  def new
    @constituency = Constituency.new
  end

  def create
    @constituency = Constituency.new(constituency_params)

    respond_to do |format|
      if @constituency.save
        format.html { redirect_to @constituency, notice: 'Constituency was successfully created.' }
        format.json { render :show, status: :created, location: @constituency }
      else
        format.html { render :new }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @constituency = Constituency.find(params[:id])
    @committee = Committee.find(params[:id])
  end

  def update
    respond_to do |format|
      if @constituency.update(constituency_params)
        format.html { redirect_to @constituency, notice: 'Constituency was successfully updated.' }
        format.json { render :show, status: :ok, location: @constituency }
      else
        format.html { render :edit }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_constituency
    @constituency = Constituency.find(params[:id])
  end

    def constituency_params
      params.require(:constituency).permit(:name, :mandate_number, :authorized_number, :empty_votes, :many_votes, :other_votes, :given_cards, :returned_cards, :voivodeship_id)
    end
end

counting_votes/app/helpers/constituencies_helper.rb
module ConstituenciesHelper
end

counting_votes/app/views/constituencies/_form.html.erb
<%= form_for(@constituency) do |f| %>
  <% if @constituency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constituency.errors.count, "error") %> prohibited this constituency from being saved:</h2>

      <ul>
      <% @constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
   <%= f.hidden_field :mandate_number, :value => @mandate_number %>
  </div>
  <div class="field">
    <%= f.hidden_field :authorized_number, :value => @authorized_number %>
  </div>
  <div class="field">
    <%= f.label :empty_votes %><br>
    <%= f.number_field :empty_votes %>
  </div>
  <div class="field">
    <%= f.label :many_votes %><br>
    <%= f.number_field :many_votes %>
  </div>
  <div class="field">
    <%= f.label :other_votes %><br>
    <%= f.number_field :other_votes %>
  </div>
  <div class="field">
    <%= f.label :given_cards %><br>
    <%= f.number_field :given_cards %>
  </div>
  <div class="field">
    <%= f.label :returned_cards %><br>
    <%= f.number_field :returned_cards %>
  </div>
  <div class="field">
    <%= f.hidden_field :voivodeship_id, :value => @voivodeship_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

counting_votes/app/views/constituencies/edit.html.erb
<h1>Add voting result</h1>


  <h2><%= @constituency.name %></h2>
  <div class="field">
    <%= f.label :committee %><br>
    <%= f.select :committee, options_for_select(Committee.all.map{|u| ["#{u.name}", u.id]}) %>
  </div>
  <div class="field">
    <%= f.hidden_field :constituency_id, :value => @constituency.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :mandate_number, :value => @mandate_number %>
  </div>
  <div class="field">
    <%= f.hidden_field :authorized_number, :value => @authorized_number %>
  </div>
  <div class="field">
    <%= f.label :empty_votes %><br>
    <%= f.number_field :empty_votes %>
  </div>
  <div class="field">
    <%= f.label :many_votes %><br>
    <%= f.number_field :many_votes %>
  </div>
  <div class="field">
    <%= f.label :other_votes %><br>
    <%= f.number_field :other_votes %>
  </div>
  <div class="field">
    <%= f.label :given_cards %><br>
    <%= f.number_field :given_cards %>
  </div>
  <div class="field">
    <%= f.label :returned_cards %><br>
    <%= f.number_field :returned_cards %>
  </div>
  <div class="field">
    <%= f.hidden_field :voivodeship_id, :value => @voivodeship.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

counting_votes/app/views/constituencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Constituencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mandate number</th>
      <th>Authorized number</th>
      <th>Empty votes</th>
      <th>Many votes</th>
      <th>Other votes</th>
      <th>Given cards</th>
      <th>Returned cards</th>
      <th>Voivodeship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constituencies.each do |constituency| %>
      <tr>
        <td><%= constituency.name %></td>
        <td><%= constituency.mandate_number %></td>
        <td><%= constituency.authorized_number %></td>
        <td><%= constituency.empty_votes %></td>
        <td><%= constituency.many_votes %></td>
        <td><%= constituency.other_votes %></td>
        <td><%= constituency.given_cards %></td>
        <td><%= constituency.returned_cards %></td>
        <% if constituency.voivodeship %>
        <td><%= constituency.voivodeship.name %></td>
        <% else %>
        <td><%= constituency.voivodeship %></td>
        <% end %>
        <td><%= link_to 'Show', constituency %></td>
        <td><%= link_to 'Edit', edit_constituency_path(constituency) %></td>
        <td><%= link_to 'Destroy', constituency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constituency', new_constituency_path %>

counting_votes/app/views/constituencies/new.html.erb
<h1>New Constituency</h1>

<%= render 'form' %>

<%= link_to 'Back', constituencies_path %>

counting_votes/app/views/constituencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @constituency.name %>
</p>

<p>
  <strong>Mandate number:</strong>
  <%= @constituency.mandate_number %>
</p>

<p>
  <strong>Authorized number:</strong>
  <%= @constituency.authorized_number %>
</p>

<p>
  <strong>Empty votes:</strong>
  <%= @constituency.empty_votes %>
</p>

<p>
  <strong>Many votes:</strong>
  <%= @constituency.many_votes %>
</p>

<p>
  <strong>Other votes:</strong>
  <%= @constituency.other_votes %>
</p>

<p>
  <strong>Given cards:</strong>
  <%= @constituency.given_cards %>
</p>

<p>
  <strong>Returned cards:</strong>
  <%= @constituency.returned_cards %>
</p>

<p>
  <strong>Voivodeship:</strong>
  <%= @constituency.voivodeship.name %>
</p>

<%= link_to 'Edit', edit_constituency_path(@constituency) %> |
<%= link_to 'Back', constituencies_path %>

counting_votes/app/views/constituencies/update.html.erb
<h1>Constituencies#update</h1>
<p>Find me in app/views/constituencies/update.html.erb</p>